title: Somesh Bose
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: httpsS://someshbose.github.io/blog/
baseurl: "/blog/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 

social:
   github: Someshbose
   #twitter: brianmaierjr
   facebook: iamsomubose
   email: iamsomeshbose@gmail.com

#google_analytics: "UA-58263416-1"
